[deps]
Catalyst = "479239e8-5488-4da2-87a7-35f2df7eef83"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OptimizationMOI = "fd9f6733-72f4-499f-8506-86b2bdd0dea1"
OptimizationNLopt = "4e6fcdb7-1186-4e1f-a706-475e75c168bb"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
